wallpaper {
  monitor = 
  path = /home/ksi/.config/hypr/img/hatsune_miku.jpg
  fit_mode = fill
}
# wallpaper{ 
#   monitor =
#   path = /home/ksi/.config/hypr/monitoring.jpg
#   fit_mode = cover
# }
